"""Write static/js/om2-sim-apps.js: every app in the MobileGym++ build, for the live card's chips.

Reads apps/*/manifest.ts and system/*/manifest.ts in the MobileGym++ checkout
(id, packageName, displayNameEn, iconBackground, iconForeground), keeps the apps
the materials' installed-apps.json lists as desktop apps, maps each to the
page's domain (om2-data.js names, with the aliases below) and marks which ones
have a PNG icon in the MobileGym CDN theme pack (the rest draw their icon in
code, so the chip shows a tile in the app's colour).

    python3 tools/extract_sim_apps.py [--checkout ../mobilegym-mock/trial_apps/mobilegym]
        [--apps ~/Downloads/mobilegympp-demo-materials-v2/apps/installed-apps.json]
"""
import argparse
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEME = "af0f7f90-04fb-417b-941e-ae7b549fe5e5"
CDN_MANIFEST = "https://cdn.mobilegym.dev/themes/manifest.json"

# page name (om2-data.js) -> simulator displayNameEn, where they differ
ALIASES = {
    "Taobao Instant Commerce": "TB Instant", "Qunar": "Qunar Travel", "NetEase Cloud Music": "NetEase Music",
    "Google Drive": "Drive", "Xianyu": "Idle Fish", "Meiyou": "Meetyou", "Vipshop": "VIP.com",
}
DOMAIN_ORDER = ["shopping", "lifestyle", "travel", "productivity", "social", "entertainment", "finance"]


def field(text, key):
    m = re.search(r"^\s*%s:\s*'([^']*)'" % key, text, re.M)
    return m.group(1) if m else None


def page_domains():
    """displayNameEn -> domain from the APPS block of om2-data.js."""
    src = (ROOT / "static/js/om2-data.js").read_text(encoding="utf-8")
    block = src[src.index("var APPS = [].concat("):src.index("emu(\"lifestyle\"")]
    out = {}
    for dom, names in re.findall(r'sim\("(\w+)",\s*\[(.*?)\]\)', block, re.S):
        for n in re.findall(r'"([^"]+)"', names):
            n = n.rstrip("*+")
            out[ALIASES.get(n, n)] = dom
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--checkout", type=Path, default=ROOT.parent / "mobilegym-mock" / "trial_apps" / "mobilegym")
    ap.add_argument("--apps", type=Path, default=Path.home() / "Downloads/mobilegympp-demo-materials-v2/apps/installed-apps.json")
    args = ap.parse_args()
    installed = {a["id"]: a for a in json.loads(args.apps.read_text(encoding="utf-8")) if a.get("desktop")}
    # the CDN answers 403 to Python's default User-Agent
    req = urllib.request.Request(CDN_MANIFEST, headers={"User-Agent": "Mozilla/5.0 (OpenMobile2-Home tools)"})
    with urllib.request.urlopen(req, timeout=30) as r:
        themes = json.load(r)["themes"]
    theme = [t for t in themes if t.get("id") == THEME][0]
    icons = set(theme.get("iconPackageNames", []))
    domains = page_domains()

    apps = {}
    for mf in list(args.checkout.glob("apps/*/manifest.ts")) + list(args.checkout.glob("system/*/manifest.ts")):
        text = mf.read_text(encoding="utf-8")
        app_id = field(text, "id")
        if app_id not in installed:
            continue
        name = installed[app_id]["displayNameEn"]
        pkg = installed[app_id]["packageName"]
        apps[app_id] = {
            "id": app_id, "name": name, "pkg": pkg,
            "color": field(text, "iconBackground") or "#334155",
            "fg": field(text, "iconForeground") or "#ffffff",
            "domain": domains.get(name, "lifestyle"),
            "system": mf.parts[-3] == "system",
            "icon": pkg in icons,
        }
    missing = [i for i in installed if i not in apps]
    if missing:
        raise SystemExit("no manifest found for: " + ", ".join(missing))
    unmapped = [a["name"] for a in apps.values() if a["name"] not in domains]
    rows = sorted(apps.values(), key=lambda a: (DOMAIN_ORDER.index(a["domain"]), a["system"], a["name"].lower()))
    lines = ["/* Generated by tools/extract_sim_apps.py from the MobileGym++ checkout:",
             "   every app in the live demo build, for the chips of the live card.",
             "   id = simulator app id, pkg = package name (PNG icon in the CDN theme",
             "   pack when icon is true), color/fg = the launcher icon's colours. */",
             "window.OM2_SIM_APPS = ["]
    for a in rows:
        lines.append("  " + json.dumps(a, ensure_ascii=False, separators=(", ", ": ")) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("];")
    (ROOT / "static/js/om2-sim-apps.js").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("%d apps written; %d with PNG icons; unmapped domains: %s" % (len(rows), sum(a["icon"] for a in rows), unmapped or "none"))


if __name__ == "__main__":
    main()
